### ISSUE TITLE
ReSharper 2017.2 Support

### ISSUE THREAD

**Issue by MattRames** [sh4/ReSharper.RpCorrector#1]
Any plans for ReSharper 2017.2 support?

**Comment by sh4** [comment]
Thank you for pointing out. I forgot R# 2017.2 support.
I just shipped R# 2017.2 supported version.
You can install from following URL or R# Extension Manager.
https://resharper-plugins.jetbrains.com/packages/ReSharper.RpCorrector/2017.2.0
